services:
  demo:
    build:
      context: .
      dockerfile: demo.dockerfile
    ports:
      - "127.0.0.1:8081:8081"
  proxy:
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8082:8082"
